"""Initial migration

Revision ID: d9bdc86c8236
Revises: 
Create Date: 2025-11-11 13:44:32.792977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bdc86c8236'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saas_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('one_liner', sa.Text(), nullable=True),
    sa.Column('target_segments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saas_info_id'), 'saas_info', ['id'], unique=False)
    op.create_index(op.f('ix_saas_info_name'), 'saas_info', ['name'], unique=True)
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('saas_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saas_info_id'], ['saas_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_index(op.f('ix_features_name'), 'features', ['name'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('related_subreddits', sa.Text(), nullable=True),
    sa.Column('saas_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saas_info_id'], ['saas_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_competitor_name'), 'leads', ['competitor_name'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('saas_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saas_info_id'], ['saas_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_plans_id'), 'pricing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_plans_plan_name'), 'pricing_plans', ['plan_name'], unique=False)
    op.create_table('reddit_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('subreddits', sa.Text(), nullable=True),
    sa.Column('lead_score', sa.Float(), nullable=True),
    sa.Column('score_justification', sa.Text(), nullable=True),
    sa.Column('generated_title', sa.String(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('posted_url', sa.String(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_posts_id'), 'reddit_posts', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_title'), 'reddit_posts', ['title'], unique=False)
    op.create_table('reddit_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('reddit_post_db_id', sa.Integer(), nullable=True),
    sa.Column('generated_reply_content', sa.Text(), nullable=True),
    sa.Column('is_replied', sa.Boolean(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reddit_post_db_id'], ['reddit_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_comments_comment_id'), 'reddit_comments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_reddit_comments_id'), 'reddit_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_comments_id'), table_name='reddit_comments')
    op.drop_index(op.f('ix_reddit_comments_comment_id'), table_name='reddit_comments')
    op.drop_table('reddit_comments')
    op.drop_index(op.f('ix_reddit_posts_title'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_id'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    op.drop_index(op.f('ix_pricing_plans_plan_name'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_id'), table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_competitor_name'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_features_name'), table_name='features')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_saas_info_name'), table_name='saas_info')
    op.drop_index(op.f('ix_saas_info_id'), table_name='saas_info')
    op.drop_table('saas_info')
    # ### end Alembic commands ###
